# Generated by Django 2.2.7 on 2019-12-18 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_user', '0002_mi_class_create_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mi_class',
            name='create_user',
            field=models.ForeignKey(on_delete='CASCADE', related_name='create_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
