# Generated by Django 2.2.7 on 2019-12-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_user', '0003_auto_20191219_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='mi_class',
            name='is_release',
            field=models.BooleanField(default=False, verbose_name='是否已发布'),
        ),
    ]
